//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schulplaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        public int BenutzerID { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Passwort { get; set; }
        public string Email { get; set; }
        public string Klasse { get; set; }
        public Nullable<int> RollenID { get; set; }
    }
}
