//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schulplaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eintraege
    {
        public int EintragsID { get; set; }
        public string Titel { get; set; }
        public string Beschreibung { get; set; }
        public System.DateTime TerminStart { get; set; }
        public System.DateTime TerminEnde { get; set; }
        public Nullable<int> ErinnerungsID { get; set; }
    
        public virtual Erinnerungen Erinnerungen { get; set; }
    }
}
