//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schulplaner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchulplanerDBEntities : DbContext
    {
        public SchulplanerDBEntities()
            : base("name=SchulplanerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benutzer> Benutzer { get; set; }
        public virtual DbSet<Eintraege> Eintraege { get; set; }
        public virtual DbSet<Erinnerungen> Erinnerungen { get; set; }
        public virtual DbSet<OeffentlicherKalender> OeffentlicherKalender { get; set; }
        public virtual DbSet<Rollen> Rollen { get; set; }
    }
}
